syntax = "proto3";

package kentik.kagent.v202401;
option go_package = "github.com/kentik/api-schema-public/gen/go/kentik/kagent/v202401;kagent";

import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/protobuf/field_mask.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

import "kentik/core/v202303/annotations.proto";
import "kentik/kagent/v202401/agent_config.proto";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "KAgent Config API"
    version: "v202401"
    contact: {
      name: "Kentik API Engineering"
      url: "https://github.com/kentik/api-schema-public"
    }
    description: "Management of Kentik Agent capability configurations: creation, retrieval, "
    "modification and deletion.\n"
  }
  external_docs: {
    url: "https://kb.kentik.com/"
    description: "Kentik Knowledge Base"
  }
  schemes: HTTPS
  consumes: "application/json"
  produces: "application/json"
  security_definitions: {
    security: {
      key: "email"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "X-CH-Auth-Email"
      }
    }
    security: {
      key: "token"
      value: {
        type: TYPE_API_KEY
        in: IN_HEADER
        name: "X-CH-Auth-API-Token"
      }
    }
  }
  security: {
    security_requirement: {
      key: "email"
      value: {}
    }
    security_requirement: {
      key: "token"
      value: {}
    }
  }
};

// =======================================================
// models
// =======================================================

// {{.Name}}
message Config {
  string name = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Name of the config."
    }
  ];
  string capability = 2 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Name of the capability the config applies to."
    }
  ];
  // config version is generated by the server
  string version = 4 [
    (google.api.field_behavior) = OUTPUT_ONLY,
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Version of the config, generated by the server."
    }
  ];
  RuntimeConfig runtime = 3 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Runtime configuration of the capability process."
    }
  ];
  // telemetry config is generated by the server
  TelemetryConfig telemetry = 5 [
    (google.api.field_behavior) = OUTPUT_ONLY,
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Telemetry configuration, generated by the server."
    }
  ];
  // config layers, seed, group, agent
  repeated ConfigLayer layers = 6 [
    (google.api.field_behavior) = OUTPUT_ONLY,
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Layers the config is composed of, in order of increasing precedence."
    }
  ];
}

// {{.Name}}
message ConfigLayer {
  // {{.Name}}
  enum LayerType {
    // Invalid value.
    LAYER_TYPE_UNSPECIFIED = 0;
    // seed config
    LAYER_TYPE_SEED = 1;
    // capability group config
    LAYER_TYPE_GROUP = 2;
    // agent config
    LAYER_TYPE_AGENT = 3;
  }

  string name = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Name of the layer."
    }
  ];
  LayerType type = 2 [
    (google.api.field_behavior) = OUTPUT_ONLY,
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Type of the layer."
    }
  ];
}

// {{.Name}}
message RuntimeConfig {
  // {{.Name}}
  message EnvVar {
    string name = 1 [
      (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
        description: "Name of the environment variable."
      }
    ];
    string value = 2 [
      (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
        description: "Value of the environment variable."
      }
    ];
    // indicates the config layer that provided this variable
    string origin = 3 [
      (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
        description: "Config layer that provided this variable."
      }
    ];
  }
  // command arguments
  repeated string args = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Command arguments passed to the process."
    }
  ];
  // environment variables
  repeated EnvVar env = 2 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Environment variables set for the process."
    }
  ];
  // binary name
  string binary = 3 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Name of the binary to run."
    }
  ];
  // linux capabilities that should be added to the process
  repeated string linux_capabilities = 4 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Linux capabilities added to the process."
    }
  ];
}

// =======================================================
// services / RPCs
// =======================================================

// {{.Name}}
message GetConfigRequest {
  string name = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Name of the config to be retrieved."
    }
  ];
}

// {{.Name}}
message GetConfigResponse {
  Config config = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Config object."
    }
  ];
}

// {{.Name}}
message DeleteConfigRequest {
  string name = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Name of the config to be deleted."
    },
    (google.api.field_behavior) = REQUIRED
  ];
}

// {{.Name}}
message DeleteConfigResponse {}

// {{.Name}}
message UpdateConfigRequest {
  Config config = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Config configuration. The `name` attribute identifies the config to be updated."
    },
    (google.api.field_behavior) = REQUIRED
  ];
  google.protobuf.FieldMask mask = 2 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Attributes of the config to be updated. Attributes not listed keep their current value."
    },
    (google.api.field_behavior) = REQUIRED
  ];
}

// {{.Name}}
message UpdateConfigResponse {
  Config config = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Updated config object."
    }
  ];
}

// {{.Name}}
message CreateConfigRequest {
  Config config = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Config configuration."
    },
    (google.api.field_behavior) = REQUIRED
  ];
}

// {{.Name}}
message CreateConfigResponse {
  Config config = 1 [
    (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = {
      description: "Created config object."
    }
  ];
}

service ConfigService {
  option (google.api.default_host) = "grpc.api.kentik.com";
  option (kentik.core.v202303.visibility) = SERVICE_VISIBILITY_PUBLIC;
  option (kentik.core.v202303.service_scope) = "ua-admin:write";

  rpc GetConfig(GetConfigRequest) returns (GetConfigResponse) {
    option (kentik.core.v202303.method_scope) = "ua-admin:read";
    option (google.api.http) = {
      get: "/kagent/v202401/config/{name}",
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      operation_id: "GetConfig"
      summary: "Get a config."
      description: "Returns the config with the specified name."
    };
  }

  rpc CreateConfig(CreateConfigRequest) returns (CreateConfigResponse) {
    option (kentik.core.v202303.method_scope) = "ua-admin:write";
    option (google.api.http) = {
      post: "/kagent/v202401/config",
      body: "config"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      operation_id: "CreateConfig"
      summary: "Create a config."
      description: "Creates a new config based on the request and returns it."
    };
  }

  rpc UpdateConfig(UpdateConfigRequest) returns (UpdateConfigResponse) {
    option (kentik.core.v202303.method_scope) = "ua-admin:write";
    option (google.api.http) = {
      patch: "/kagent/v202401/config/{config.name}",
      body: "*"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      operation_id: "UpdateConfig"
      summary: "Update a config."
      description: "Updates the attributes of a config selected by the field mask in the request."
    };
  }

  rpc DeleteConfig(DeleteConfigRequest) returns (DeleteConfigResponse) {
    option (kentik.core.v202303.method_scope) = "ua-admin:write";
    option (google.api.http) = {
      delete: "/kagent/v202401/config/{name}"
    };
    option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
      operation_id: "DeleteConfig"
      summary: "Delete a config."
      description: "Deletes the config with the specified name."
    };
  }
}
